apiVersion: v1
name: ogm-insy
description: A Helm chart for OGM.Insy Streamlit application
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - ai
  - streamlit
  - semantic-search
  - multimodal
home: https://github.com/mksaraf/ogm.github.insy
sources:
  - https://github.com/mksaraf/ogm.github.insy
maintainers:
  - name: mksaraf
    email: mksaraf@example.com